# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cicada < Formula
  desc "TUI analytics dashboard for Claude Code sessions"
  homepage "https://github.com/base-14/cicada"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/base-14/cicada/releases/download/v0.2.1/cicada_0.2.1_darwin_amd64.tar.gz"
      sha256 "8f4dc7a01cf5a79cbbba5204d19da236ea2ff70c1c39624fb82f3a6059a8e50f"

      define_method(:install) do
        bin.install "cicada"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/base-14/cicada/releases/download/v0.2.1/cicada_0.2.1_darwin_arm64.tar.gz"
      sha256 "ebe5418a1da7b669887f5a69db4bbb3f1d98723b0f2518ec40a4aa33efa240be"

      define_method(:install) do
        bin.install "cicada"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/base-14/cicada/releases/download/v0.2.1/cicada_0.2.1_linux_amd64.tar.gz"
      sha256 "00d88ce99bcc01807b05656e7939dbbf48cd690eefafa7cdddd4177adf78bdf9"
      define_method(:install) do
        bin.install "cicada"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/base-14/cicada/releases/download/v0.2.1/cicada_0.2.1_linux_arm64.tar.gz"
      sha256 "fccd3ccbf96aee48c927156eef09d3730f6c855be0a995f7860a4cdd11e9fb2f"
      define_method(:install) do
        bin.install "cicada"
      end
    end
  end
end
