# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cicada < Formula
  desc "TUI analytics dashboard for Claude Code sessions"
  homepage "https://github.com/base-14/cicada"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/base-14/cicada/releases/download/v0.2.1/cicada_0.2.1_darwin_amd64.tar.gz"
      sha256 "eec99fd89b3c9f98e31c902691a93ab495462c1605a48add9fe5eb4c195156e3"

      define_method(:install) do
        bin.install "cicada"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/base-14/cicada/releases/download/v0.2.1/cicada_0.2.1_darwin_arm64.tar.gz"
      sha256 "95567af009224a0340db4b03e8bf1119df30ed288a6b0b9585b163d58de2c51a"

      define_method(:install) do
        bin.install "cicada"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/base-14/cicada/releases/download/v0.2.1/cicada_0.2.1_linux_amd64.tar.gz"
      sha256 "d5c3ab3f580df57fbfe464a06704a2e16208f59c35887f3481be7f7d8e4e520c"
      define_method(:install) do
        bin.install "cicada"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/base-14/cicada/releases/download/v0.2.1/cicada_0.2.1_linux_arm64.tar.gz"
      sha256 "44e8405e02ab7ebfdd686cd3787fc8150e63960033d435307fdfd3210b411ca1"
      define_method(:install) do
        bin.install "cicada"
      end
    end
  end
end
